### PR TITLE
feat: add van gelder end-user

### PR DESCRIPTION
**Pull request by stijnmoreels**
Add Van Gelder end-user via @pim-simons.

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@pim-simons do we have their permission to publish their logo?

**Comment by pim-simons** [comment]
> 
> 
> @pim-simons do we have their permission to publish their logo?

Yes, I have asked and received their permission 👍🏻

**Comment by tomkerkhove** [comment]
Awesome, thanks!

**Review by tomkerkhove — APPROVED** [review]
LGTM, but can you align the image sizes as it's a bit big in the preview (mobile)

**Comment by stijnmoreels** [comment]
> LGTM, but can you align the image sizes as it's a bit big in the preview (mobile)

Aha, yeah, resized it to 267x100 (100 seems to be the right height the other logo's are using).

**Pull request merged**
