### PR TITLE
chore: sharpen arcus diagrams

### PR DESCRIPTION
**Pull request by stijnmoreels**
Sharpen those Arcus diagrams!

### CODE REVIEW

**Review by THMKAE — APPROVED** [review]

**Review by pim-simons — APPROVED** [review]
🏆

**Review by fgheysels — COMMENTED** [review]
There were 2 smaller images present (approx 640 x 100px) that have now been replaced by larger images.  Isn't that going to pose a problem ?

**Comment by stijnmoreels** [comment]
> There were 2 smaller images present (approx 640 x 100px) that have now been replaced by larger images. Isn't that going to pose a problem ?

I imagine it will stretch like the other images to the available space.

**Comment by THMKAE** [comment]
> > There were 2 smaller images present (approx 640 x 100px) that have now been replaced by larger images. Isn't that going to pose a problem ?
> 
> I imagine it will stretch like the other images to the available space. Previously, it was only that those smaller images were stretched until it was pixellated.

This will indeed be the case. When these are added to the preview, I'll also add them to the new website as well, making sure it's not super slow downloading those. I can always make them a bit smaller, but I cannot make them bigger (without losing quality).

**Comment by fgheysels** [comment]
Ok, just wanted to be sure.

**Review by fgheysels — APPROVED** [review]

**Pull request merged**
