### PR TITLE
docs: Feature/new website (❗)

### PR DESCRIPTION
**Pull request by THMKAE**
## Description
This PR features a new website within the `/website` folder, it can be moved to `docs` later, but to keep git changes clean I used a new folder.

The `README.md` of the website folder explains how to update/add new content to the site. I've tried to keep it as similar as possible to the old way of working, so you still are able to use regular markdown files to add f.e. blog posts.

The site is build with Next.js and uses a static export, which means it'll create all required html pages on build time in the `out` folder.

Updating pages content is also possible with basic markdown, but it uses `.mdx` files which are JSX powered markdown files, basically meaning you can use React components in it. But I also explained this thoroughly in the `README.md`.

All blog posts and components are migrated with the addition of template type components that are used on the homepage as highlighted features (they also use a different icon). Use cases and some other content (more or less) is synced with the `preview` folder.

It is important to verify all content on the site and update where needed. For example the "arcus" vs "Arcus" we discussed.
Currently the description of the component isn't unique, al lot of them have the "...in a breeze" description. Might be best to give them all a more specific description.

I've updated the `netlify.toml` file to use the new folder instead of the old one, but this might need some updates.

If you have any questions, please let me know!

### CODE REVIEW

**Review by stijnmoreels — APPROVED** [review]
In a later phase, we could then remove the old website resources, right?
It's already a good thing to have this separate, thx for that! And also thx for the great work here. Looks real nice!

Was wondering if we could use ✔ signs with the advantages instead of bullet points?

**Comment by THMKAE** [comment]
> In a later phase, we could then remove the old website resources, right?

Yes, or move them to the `docs` folder

> Was wondering if we could use ✔ signs with the advantages instead of bullet points?

Should be possible, I'll have a look at it when I can find some time

**Comment by THMKAE** [comment]
@stijnmoreels I've added the ✓ symbol to the list of the right aligned sections, which means it is only active on the "Why Arcus?" (for now)
You can see it in the preview. If you rather use this ✔ symbol instead, let me know.

Imho, I don't think it is an improvement and prefer the regular bullet points, but that's just my opinion.

**Comment by stijnmoreels** [comment]
> Imho, I don't think it is an improvement and prefer the regular bullet points, but that's just my opinion.

If you think that bullet points are better, you can change it back. I trust your instincts. 😉

**Review by pim-simons — APPROVED** [review]
Looks really good to me 👍🏻 🥇

**Comment by stijnmoreels** [comment]
@fgheysels , could you give some feedback on this, so we can complete this one, thx!

**Comment by fgheysels** [comment]
Really a nice site!

I do have some feedback though, but nothing that would keep us from completing this PR:
- I think the different Arcus components are ordered alphabetically.  Should we change that order to something more custom.  For instance, put the more popular components first ?
- On the website, different components are discussed, and we have a title 'why not use the Microsoft package'.  It is good to have that there, but maybe we should also mention that Arcus is built on top of those Microsoft packages ?

But all in all, really nice work!

**Review by fgheysels — APPROVED** [review]

**Comment by stijnmoreels** [comment]
> I think the different Arcus components are ordered alphabetically. Should we change that order to something more custom. For instance, put the more popular components first ?

If we have control over the order ourselves, we can change this indeed. Maybe something like we control the side-bar tabs (`02-Features/`, `01-Guides/`...)?

> On the website, different components are discussed, and we have a title 'why not use the Microsoft package'. It is good to have that there, but maybe we should also mention that Arcus is built on top of those Microsoft packages ?

We could improve this indeed a bit, but not blocking as this PR is more about the new website, not specifically about the content.

**Comment by THMKAE** [comment]
> > I think the different Arcus components are ordered alphabetically. Should we change that order to something more custom. For instance, put the more popular components first ?
> 
> If we have control over the order ourselves, we can change this indeed. Maybe something like we control the side-bar tabs (`02-Features/`, `01-Guides/`...)?

This should work out-of-the-box just by updating the filenames, all content is taken from the frontmatter block anyway.
It'll change the order on both the home and component page.

OR

We implement it like we do with `resources/use-cases` where there is an `order` property in the frontmatter block.
Needs a small code change.
```markdown
---
title: Simplify telemetry tracking with contextual information
slug: simplify-telemetry-tracking-with-contextual-information
order: 1
description: Tracking telemetry with useful information is not an easy task. Giving each telemetry instance enough contextual information, correlated with other telemetry...
components:
  - Arcus Observability
---
```

**Comment by stijnmoreels** [comment]
> This should work out-of-the-box just by updating the filenames, all content is taken from the frontmatter block anyway.
It'll change the order on both the home and component page.

I would like this out-of-the-box approach, as you do not need to open the file to do that. 😄

**Pull request merged**
