### PR TITLE
Provide new template for our documentation

### PR DESCRIPTION
**Pull request by tomkerkhove**
Provide new template for our documentation which lists all components and foundation for our use-cases

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@SamVanhoutte  @stijnmoreels I recommend just going to https://5fc4bd21680a4c0007c7296e--arcus-staging.netlify.app/ and reviewing that.

**Comment by tomkerkhove** [comment]
Removed `arcus-azure-refresh` temporary Netlify app

**Comment by stijnmoreels** [comment]
> @SamVanhoutte @stijnmoreels I recommend just going to https://5fc4bd21680a4c0007c7296e--arcus-staging.netlify.app/ and reviewing that.

Well, I think that's very good.

**Comment by SamVanhoutte** [comment]
Looks great - might be nice to include a link to the blog posts as well, as they contain a lot of good contextual information

**Comment by tomkerkhove** [comment]
Good idea, done in https://github.com/arcus-azure/arcus/pull/103

**Pull request merged**
