### PR TITLE
chore: Remove @tomkerkhove as code owner

### PR DESCRIPTION
**Pull request by tomkerkhove**
Unfortunately, I don't have the time that I was hoping to have which means that I can no longer actively contribute - Sorry!

Feel free to remove me from the rest as well.

### CODE REVIEW

**Comment by stijnmoreels** [comment]
Yes, of course, understandable. Thx for any contributions and feel free to take a peek when you feel like it :wink.

**Review by stijnmoreels — APPROVED** [review]

**Comment by tomkerkhove** [comment]
I certainly will! Thanks and happy to see it keep on growing!

**Comment by SamVanhoutte** [comment]
@tomkerkhove , thank you indeed!  and don't hesitate to leverage and use Arcus, wherever you seem applicable

**Comment by tomkerkhove** [comment]
I certainly will!

**Pull request merged**
